services:
  - type: web
    name: airbnb-backend
    runtime: node
    env: node
    rootDir: airbnb
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: ATLASDB_URL
        sync: false
      - key: SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://airbnbui-fxxu.onrender.com